_langs = {};
_langs['ar'] = {
    "arabic": "عربي",
    "english": "English",
    "all": "الكل",
    "title": "القرآن الكريم للجوال ",
    "desc": "مشروع قرآني شامل بمميزات فريدة",
    "sura_s": "سورة",
    "aya_s": "آية",
    "sura": "السورة",
    "aya": "الآية",
    "page": "الصفحة",
    "juz": "الجزء",
    "hizb": "الحزب",
    "arbaa": "الأرباع",
    "first_hizb": "الحزب الأول",
    "second_hizb": "الحزب الثاني",
    "sowar": "السور",
    "ayat": "الآية",
    "pages": "الصفحات",
    "agzaa": "الأجزاء",
    "ahzab": "الأحزاب",
    "qaree": "القارئ",
    "from": "من",
    "to": "إلى",
    "menu_key": "القائمة",
    "download": "تنزيل",
    "cancel": "إلغاء",
    "hide":"إخفاء",

    "bu_download_cnt": "تنزيل الملحقات",
    "bu_download_images": "الصفحات",
    "bu_download_recites": "التلاوات",
    "bu_download_ttarajem": "التفاسير",
    "bu_download_app": "تنزيل التطبيق",
    "bu_lang": "English",
    "bu_lang_link": "en",
    "bu_browse": "التصفح والبحث",
    "bu_tafaser": "التفاسير والمعاني",
    "bu_telawa": "التلاوة والتحفيظ",
    "close": "إغلاق",
    "start": "بدء",

    "pcview": "الوضع الرئيسي",
    "options": "الخيارات",
    "settings": "الإعدادات",
    "help": "المساعدة",
    "bu_help": "مساعدة", // rem
    "browsesearch": "التصفح والبحث",
    "search": "البحث",
    "chooseSura": "إختيار السورة",
    "chooseAya": "إختيار الآية",
    "go": "إنتقل",
    "chooseJuz": "إختيار الجزء",
    "chooseHizb": "إختيار الحزب",
    "quarter": "الربع",
    "first_quarter": "الربع الأول",
    "second_quarter": "الربع الثاني",
    "third_quarter": "الربع الثالث",
    "fourth_quarter": "الربع الرابع",
    "enterPageNum": "رقم الصفحة",

    "doSearch": "إبحث",
    "search_holder": "بحث في نصوص الآيات",
    "searchResults": "نتائج البحث",
    "search_err_length": "عفوا كلمة البحث يجب ألا تقل عن 3 أحرف",
    "search_nores": "عفوا لا توجد نتائج للبحث",
    "search_resof": "نتائج البحث عن عبارة ",
    "tafsir": "التفسير",
    "tafaser": "التفاسير",
    "chooseTafsir": "اختيار التفسير",
    "browse": "استعرض",
    "viewingTafsir": "عرض التفسير",
    "tafsir_sa3dy": "السعدي",
    "tafsir_waseet": "الوسيط لطنطاوي",
    "tafsir_katheer": "ابن كثير",
    "tafsir_kortoby": "القرطبي",
    "tafsir_tabary": "الطبري",
    "tafsir_ba3awy": "البغوي",
    "tafsir_e3rab": "إعراب القرآن - قاسم دعاس",
    "tafsir_tafheem": "تفهيم القرآن - إنجليزي",
    "tafsir_indonesian": "الجلالين مترجم للأندونيسية",
    "tafsir_russian": "السعدي مترجم للروسية",
    "tafsir_browse": "استعرض",
    "trans": "التراجم والمعاني",
    "chooseTrans": "اختيار الترجمة",
    "telawa": "التلاوة والتحفيظ",
    "telawat": "التلاوات",
    "chooseQaree": "إختيار القارئ",
    "chooseVTrans": "الترجمة الصوتية",
    "vtrans_null": "بدون",
    "autoStop": "توقف تلقائي",
    "autoStop_null": "بدون",
    "autoStop_sura": "نهاية السورة",
    "autoStop_page": "نهاية الصفحة",
    "autoStop_juz": "نهاية الجزء",
    
    "autoStop_page_msg":"تم تفعيل الإيقاف التلقائي عند نهاية الصفحة",
    "autoStop_sura_msg":"تم تفعيل الإيقاف التلقائي عند نهاية السورة",
    "autoStop_juz_msg":"تم تفعيل الإيقاف التلقائي عند نهاية الجزء",
    
    "autoStop_deactivate":"إلغاء الإيقاف التلقائي",

    
    "activateRepeat": "تفعيل التكرار",
    "deactivateRepeat": "إلغاء التكرار",
    "deterStart": "تحديد البدء",
    "deterStartSura": "سورة البدء",
    "deterStartAya": "آية البدء",
    "deterEnd": "تحديد الانتهاء",
    "deterEndSura": "سورة الانتهاء",
    "deterEndAya": "آية الانتهاء",
    "repeat": "التكرار",
    "repeat_forAya": "التكرار للآية",
    "repeat_forAya_null": "بدون تكرار",
    "repeat_waiting": "الانتظار",
    "repeat_waiting_null": "بدون انتظار",
    "repeat_waiting_short": "انتظار قصير",
    "repeat_waiting_medium": "انتظار متوسط",
    "repeat_waiting_long": "انتظار طويل",
    "repeat_forAll": "التكرار للفقرة",
    "repeat_forAll_null": "بدون تكرار",
    "repeat_settings": "إعدادات التكرار",

    "recite_cats": "أقسام التلاوات",

    "recite_hq": "جودة صوت عالية",
    "recite_hcon": "للاتصالات السريعة",
    "recite_mq": "جودة متوسطة",
    "recite_mcon": "للاتصالات البطيئة",
    "recite_mujawwad": "مجود",
    "recite_moalim": "معلم",
    "recite_warsh": "ورش",
    "recite_kh_res": "خليفة الطنيجي - المصحف المعلم، متوفر آخر خمسة أجزاء فقط",
    "recite_trans": "التراجم الصوتية",
    "recite_sudais": "عبد الرحمن السديس",
    "recite_shuraym": "سعود الشريم",
    "recite_maher": "ماهر المعيقلي",
    "recite_husary": "الحصري",
    "recite_banna": "محمود علي البنا",
    "recite_jibreel": "محمد جبريل",
    "recite_shaatree": "أبو بكر الشاطري",
    "recite_ajamy": "أحمد العجمي",
    "recite_afasy": "مشاري العفاسي",
    "recite_basfar": "عبد الله بصفر",
    "recite_minshawy": "المنشاوي",
    "recite_ayyoub": "محمد أيوب",
    "recite_rifai": "هاني الرفاعي",
    "recite_tablawy": "الطبلاوي",
    "recite_hudhaify": "الحذيفي",
    "recite_abdul_basit": "عبد الباسط",
    "recite_ghamadi": "سعد الغامدي",
    "recite_qatami": "ناصر القطامي",
    "recite_yaser": "ياسر الدوسري",
    "recite_akhdar": "إبراهيم الأخضر",
    "recite_juhanee": "عبد الله عواد الجهني",
    "recite_muhsin": "عبد المحسن القاسم",
    "recite_khaleefa": "خليفة الطنيجي",
    "recite_yassin": "ياسين الجزائري",
    "recite_ibrahim_dosary": "إبراهيم الدوسري",
    "recite_abbad": "فارس عباد",
    "recite_salamah": "ياسر سلامة",
	"recite_jaber": "علي عبد الله جابر",
    "recite_ayman": "أيمن سويد",
    
    "menu_hint": "القائمة الرئيسية",
    "chooseAya_hint": "لاختيار الآية يرجى النقر لمدة طويلة",

    "flash_needed": "قد تحتاج لمشغل الفلاش لتتمكن من الاستماع",
    "trans_ctrl_msg": "حرك لأعلى أو لأسفل",
    "fontsize": "حجم الخط",
    "trans_ctrl_choose": "تغيير الترجمة",
    "about_title": "مساعدة",
    "about_cont": "هذه هي الواجهة المخصصة للجوالات الذكية والحواسب الكفية من مشروع المصحف الإلكتروني بجامعة الملك سعود , المشروع متوفر أيضا في واجهة مخصصة للحواسب التقليدية ونسخة قابلة للتنزيل على الحواسب التقليدية برنامج آيات",
    "contact_mi": "اتصل بنا",
    "contact_title": "اتصل بنا",
    "contact_name": "الاسم",
    "contact_email": "البريد الالكتروني",
    "contact_msg": "الرسالة",
    "contact_send": "إرسال",
    "contact_done": "تم الارسال بنجاح وإن شاء الله نوافيكم بالرد - إن دعت الحاجة - فور المراجعة",
    "contact_err_name": "عفوا تأكد من كتابة الاسم",
    "contact_err_email": "عفوا تأكد من كتابة البريد",
    "contact_err_msg": "عفوا تأكد من كتابة الرسالة",
    "contact_err_failed": "عفوا لم يتم الارسال، نرجو المحاولة لاحقا",
    "unsub_twitter": "لطلب الغاء الاشتراك من تطبيق آيات في تويتر يرجى إرسال عنوان الحساب الخاص بكم على تويتر",

    "mosshaf_type": "المصحف",
    "mosshaf_hafs": "حفص عن عاصم",
    "mosshaf_tajweed": "حفص عن عاصم - مصحف التجويد",
    "mosshaf_warsh": "رواية ورش عن نافع",
    "view_type": "واجهة الاستخدام",
    "view_mobile": "واجهة الجوال",
    "view_pc": "واجهة الحاسب",
    "choose_lang": "اللغة",
    "l_arabic": "عربي",
    "l_english": "English",
    "fnf_audio": "عفوا ملف الصوت غير موجود ولا يمكن تنزيله - فضلا تأكد من الإتصال بالانترنت",
    "fnf_image": "عفوا ملف الصورة غير موجود ولا يمكن تنزيله - فضلا تأكد من الإتصال بالانترنت",
    "close_app": "إغلاق التطبيق؟",
    "close_app_downs": "إغلاق التطبيق ام إخفائه؟ ، مع العلم ان اغلاقه سيقطع عملية تنزيل المحتوى واخفائه سيبقي على البرنامج يعمل في الخلفية ",
    "sd_nf": "عفوا البرنامج يتطلب وجود كارت التخزين SD card",
    "page_num1604": "عفوا يرجى إدخال رقم بين 1 و 604",
    "repeat_notifyAway": "عفوا تحاول الإنتقال لآية خارج حدود التكرار ، فهل ترغب في إيقاف التكرار",
    "repeat_notifyStop": "عفوا يتوجب إلغاء التكرار الحالي لتتمكن من التعديل",
    "alert_defTitle": "تنبيه",
    "alert_ok": "تم",
    "alert_next": "التالي",
    "yes": "نعم",
    "no": "لا",
    "downSlowNote": "رجاء الإنتباه ، قد تلاحظ بطئ في عمل البرنامج أثناء عملية تنزيل المحتوى ، سيزول هذا البطئ بمجرد إكتمال التنزيل",
    "welcome": "مرحبا",
    "intro1": '<p align="center">بسم الله الرحمن الرحيم</p><div><b>آيات</b> : هو برنامج قرآني شامل بمميزات فريدة </div>',
    "intro2": "لكي تتمتع بكافة مميزات البرنامج دون الحاجة للإتصال بالانترنت، تحتاج لتنزيل ملفات الصور ، والتلاوات ، والتفاسير والتراجم على جهازك",
    "intro3": 'يمكنك البدء في تنزيل المحتوى عبر الضغط على زر "تنزيل المحتوى" الموجود بالقائمة الرئيسية',
    "intro4": "مزيد من الشرح والإيضاح متوفر عبر النقر على زر 'المساعدة' في القائمة الرئيسية <p>ندعو الله عز وجل أن ينفعنا وإياكم بهذا البرنامج ، ونرجو ألا تنسونا من صالح دعائكم</p>",
    "help_main_mi": "شرح الاستخدام",
    "help_features_mi": "المميزات",
    "help_about_mi": "حول البرنامج",
    "help_mi": "المساعدة",
    "pls_wait": "رجاء الإنتظار للحظات",
    "favs": "العلامات المرجعية",
    "noFavs": "لا توجد علامات مرجعية",
    "addFav": "علامة",
    "fav_alert": "إضافة علامة مرجعية",
    "fav_read":"القراءة",
    "fav_memo":"الحفظ",
    "fav_readPos":"موضع القراءة",
    "fav_memoPos":"موضع الحفظ",
    "fav_date":"بتاريخ",
   
    "note": "ملاحظة",
    "optional": "إختياري",
    
    "mtest": "اختبار الحفظ",
    "mtest_ques": "سؤال جديد",

    "buAddFav": "إضافة",
    "remFav": "إزالة العلامة",
    "fav_added": "تم إضافة العلامة المرجعية يمكنك استعراض العلامات المرجعية عبر قائمة التصفح والبحث",
    "fav_exist": "الآية موجودة بالفعل ضمن قائمة العلامات المرجعية هل ترغب في إزالة العلامة المرجعية",
    "copy": "نسخ",
    "copy_nextAya": "الآية التالية",
    "copy_tashkeel": "التشكيل",
  
    "copyWOT": "نسخ بدون تشكيل",
    "send": "إرسال",
    "sendWOT": "إرسال بدون تشكيل",
    "sendSMS": "برسالة نصية",
    "sendMail": "بالبريد",
    "share": "مشاركة",
    "shareFB": "فيس بوك",
    "shareTwit": "تويتر",
    "shareApp_bu": "نشر التطبيق",
    "shareApp_msg": "مشروع المصحف الإلكتروني - آيات - للحاسوب والجوال، يوفر ميزة القراءة والتلاوة والتفسير والتحفيظ، يمكنك التصفح من الانترنت مباشرة او تثبيته على جهازك : http://quran.ksu.edu.sa",
    "rateApp_bu": "تقييم التطبيق",
    "bu_closeApp": "إخفاء التطبيق",
    "bu_exitApp": "إغلاق التطبيق",
    "bright_type": "مستوى السطوع",
    "bright_high": "سطوع عالي",
    "bright_med": "سطوع متوسط",
    "vision_type": "طريقة القراءة",
    "vision_normal": "قراءة عادية",
    "vision_night": "قراءة ليلية",
    "hint_1": "يمكنك تحديد الآية عن طريق النقر المزدوج او الضغط لمدة طويلة",
    "hint_2": "ستظهر لك قائمة بالأسفل خاصة بالآية المحددة، تمكنك من الاستماع للتلاوة وعرض التفسير",
    "hint_pls_download": "ينصح بالبدء بتنزيل ملفات الصور والتلاوة والتفاسير لكي تتمكن من استخدام التطبيق دون اتصال بالانترنت",
    "hpd_ok": "تنزيل المحتوى",
    "hpd_no": "ليس الآن",
    "notify_mob_interface": 'هذه الواجهة مخصصة لأجهزة الجوال ، يمكنك الانتقال لواجهة الحاسوب من خلال <a href="http://quran.ksu.edu.sa/index.php?ui=1" class="ext">هذا الرابط</a>',
    "confirm_warsh": " هل ترغب في عرض المصحف برواية ورش عن نافع ؟ ",
    "confirm_restartApp": "لتفعيل هذا الإعداد يحتاج التطبيق للإغلاق وإعادة التشغيل مرة أخرى هل ترغب في إغلاقه الآن",

    "setting_keeplight": "الإبقاء على إضاءة الشاشة",
    "setting_keepworking": "عمل التطبيق بعد غلق الشاشة",
    "setting_showstatus": "إظهار شريط الساعة والتنبيهات",
    "setting_shouldext": "حفظ التلاوات على",
    "setting_extsd": "الذاكرة الخارجية",
    "setting_intsd": "الذاكرة الداخلية",
    
    "extsd_nf" : "عفوا تطبيق آيات لم يتمكن من التعرف على كارت الذاكرة الخارجي",

    
    
    "download_resumeBu": "استمرار",
    "download_pauseBu": "إيقاف",
    "download_stopBu": "إلغاء",
    "download_compBu": "اكتمل التنزيل",
    "download_pages_from": "من صفحة",
    "download_pages_to": "إلى صفحة",
    "download_masahef": "المصحف",
    "download_ttarajem": "التفاسير والتراجم",
    "download_ttarajem_tafaser": "التفاسير",
    "download_ttarajem_tarajem": "التراجم",
    "chk_conn": "فشل الاتصال بالسيرفر، فضلا تأكد من الاتصال بالانترنت",

    "confirm_download_tafsir": "ملف التفسير غير متوفر لديك هل ترغب في تنزيله أم القراءة مباشرة عبر الانترنت",
    "confirm_download_trans": "ملف الترجمة غير متوفر لديك هل ترغب في تنزيله أم القراءة مباشرة عبر الانترنت",
    "confirm_download_pages": "بعض صفحات المصحف غير متوفرة لديك هل ترغب في تنزيلها الآن",

    "confirm_update_tafsir": "يتوفر تحديث لملف التفسير به معالجة للأخطاء الإملائية المكتشفة هل ترغب في تنزيله الآن",
    "confirm_update_trans": "يتوفر تحديث لملف الترجمة به معالجة للأخطاء الإملائية المكتشفة هل ترغب في تنزيله الآن",

    "direct_read": "قراءة مباشرة",
    "download_file": "تنزيل الملف",

    "copy_done": "تم النسخ",
    "copy_failed": "عفوا لم يتم النسخ",

    "sentViaAyat": "تم الإرسال عبر تطبيق آيات",
    "ayaLink": "رابط القراءة والتفسير والتلاوة",

    "mozaker": "المنبه",
    "mozaker_msg": "رسالة_التنبيه",
    "mozaker_msg_default": "ورتل القرآن ترتيلا",
    
    "mozaker_alert": "صوت_التنبيه",
    "mozaker_alert_null": "بدون",
    "mozaker_alert_default": "التنبيه الإفتراضي",

    "mozaker_null": "غير مفعل",

    "mozaker_morning": "صباحا",
    "mozaker_noon": "ظهرا",
    "mozaker_evening": "مساءا",
    "mozaker_night": "ليلا",
    
    "mozaker_am": "ص",
    "mozaker_pm": "م",
    
    
    
    "ayatApp": 'تطبيق آيات',
    "downloadingRecite": 'تنزيل التلاوة',
    "downloadingReciteComped": 'إكتمل تنزيل التلاوة',
    "downloadingRecitePaused": 'توقف تنزيل التلاوة',
    "recitation": "التلاوة",
    "forReciter":'للقارئ',
    "downloadingPages":"تنزيل الصفحات",
    "downloadingPagesComped":"إكتمل تنزيل الصفحات",
    "downloadingPagesPaused":"توقف تنزيل الصفحات",
    "downloadingTTafasir":"تنزيل التفاسير والتراجم"
};

_langs['en'] = {
    "arabic": "عربي",
    "english": "English",
    "all": "All",
    "title": "Al Quran for mobile",
    "desc": "Comprehensive Quranic project with unique features.",
    "sura": "Sura",
    "aya": "Aya",
    "sura_s": "Sura",
    "aya_s": "Aya",
    "page": "Page",
    "juz": "Juz",
    "hizb": "Hizb",
    "arbaa": "Arbaa",
    "first_hizb": "First Hizb",
    "second_hizb": "Second Hizb",
    "sowar": "Sura",
    "ayat": "Ayas",
    "pages": "Pages",
    "agzaa": "Juz",
    "ahzab": "Hizb",
    "qaree": "Reciter",
    "from": "from",
    "to": "to",
    "menu_key": "Menu",
    "download": "Download",
    "cancel": "Cancel",
    "hide":"Hide",
    
    "bu_download_cnt": "Download contents",
    "bu_download_images": "Pages",
    "bu_download_recites": "Recites",
    "bu_download_ttarajem": "Transes",

    "bu_download_app": "Download App",
    "bu_lang": "عربي",
    "bu_lang_link": "ar",
    "bu_browse": "Browse",
    "bu_tafaser": "Tafaser & Translations",
    "bu_telawa": "Reciting & Memorizing",
    "close": "Close",
    "start": "Start",

    "pcview": "PC View",
    "options": "Options",
    "settings": "Settings",
    "help": "Help",
    "bu_help": "Help", // rem
    "browsesearch": "Browsing",
    "search": "Search",
    "chooseSura": "Choose Sura",
    "chooseAya": "Choose Aya",
    "go": "Go",
    "chooseJuz": "Choose Juz",
    "chooseHizb": "Choose Hizb",
    "quarter": "Quarter",
    "first_quarter": "First Quarter",
    "second_quarter": "Second Quarter",
    "third_quarter": "Third Quarter",
    "fourth_quarter": "Fourth Quarter",
    "enterPageNum": "Page Number",
    "doSearch": "Search",
    "search_holder": "Search Al Quran",

    "searchResults": "Search Results",
    "search_err_length": "Search query must be more than 3 characters",
    "search_nores": "no results",
    "search_resof": "results for the phrase ",
    "tafsir": "Tafsir",
    "tafaser": "Tafaser",
    "chooseTrans": "Choose Translation",
    "chooseTafsir": "Choose Tafsir",
    "browse": "View",
    "viewingTafsir": "Viewing Tafsir",
    "tafsir_sa3dy": "Al-Saadi",
    "tafsir_waseet": "AlWaseet -Tantawy",
    "tafsir_katheer": "Ibn Katheer",
    "tafsir_kortoby": "Al-Qurtobi",
    "tafsir_tabary": "Al-Tabri",
    "tafsir_ba3awy": "Al-Baghawy",
    "tafsir_tanweer": "Ibn Ashour",
    "tafsir_e3rab": "E'rab Al-Quran",
    "tafsir_tafheem": "English - Tafheem",
    "tafsir_indonesian": "Indonesian - Tafsir Jalalayn",
    "tafsir_russian": "русский (Russian) Кулиев - ас-Саади",
    "tafsir_browse": "browse",
    "trans": "Translations",
    "telawa": "Recitation",
    "telawat": "Recitations",
    "chooseQaree": "Choose Reciter",
    "chooseVTrans": "Voice Translation",
    "vtrans_null": "none",
    "autoStop": "Auto stop",
    "autoStop_null": "none",
    "autoStop_sura": "End of Sura",
    "autoStop_page": "End of Page",
    "autoStop_page_msg":"Auto stop at the end of the page activated",
    "autoStop_sura_msg":"Auto stop at the end of the sura activated",
    "autoStop_juz_msg":"Auto stop at the end of the juz activated",
    
    "autoStop_deactivate":"Deactivate",
    "activateRepeat": "Activate Repeating",
    "deactivateRepeat": "Deactivate Repeating",
    "deterStart": "Start At",
    "deterStartSura": "Sua",
    "deterStartAya": "Aya",
    "deterEnd": "End At",
    "deterEndSura": "Sura",
    "deterEndAya": "Aya",
    "repeat": "Repeating",
    "repeat_forAya": "Repeat for Aya",
    "repeat_forAya_null": "No Repeat",
    "repeat_waiting": "Delay Time",
    "repeat_waiting_null": "No Delay",
    "repeat_waiting_short": "Short Delay",
    "repeat_waiting_medium": "Medium Delay",
    "repeat_waiting_long": "Long Delay",
    "repeat_forAll": "Repeat for Range",
    "repeat_forAll_null": "No Repeat",
    "repeat_settings": "Repeat settings",
    "recite_cats": "Recites categories",
    
    "recite_hq": "High Quality",
    "recite_hcon": "for fast connections",
    "recite_mq": "Medium Quality",
    "recite_mcon": "Slow connection",
    "recite_mujawwad": "Mojawwad",
    "recite_moalim": "Teacher",
    "recite_warsh": "Warsh",
    "recite_kh_res": "Khaleefa Al-Tunaiji teacher recitation, available for last five parts only",
    "recite_trans": "Voice Translation",
    "recite_sudais": "AbdullRahman Al-Sudais",
    "recite_shuraym": "Saud Al-Shoraim",
    "recite_maher": "Maher Al-moaqeli",
    "recite_husary": "Al-Husari",
    "recite_banna": "Mahmoud Ali Al-Banna",
    "recite_jibreel": "Mohammad Jebreil",
    "recite_shaatree": "Abu Baker Al-shatrei",
    "recite_ajamy": "Ahmad Al-ajami",
    "recite_afasy": "Mishari Al-efasi",
    "recite_basfar": "Abdullah Basfar",
    "recite_minshawy": "Al-Menshawy",
    "recite_ayyoub": "Mohammad Ayoub",
    "recite_rifai": "Hani Al-Refaei",
    "recite_tablawy": "Al-Tabalawi",
    "recite_hudhaify": "Al-Huthaify",
    "recite_abdul_basit": "Abdullbaset",
    "recite_ghamadi": "Saad Al-Ghamidi",
    "recite_qatami": "Nasser Al-Qatami",
    "recite_yaser": "Yaser Al-Dosary",
    "recite_abbad": "Fares Abbad",
    "recite_salamah": "Yaser Salamah",
	"recite_jaber": "Ali Abd-Allah Jaber",	
    "recite_ayman": "Ayman Sowaid",
    
    "recite_akhdar": "Ibrahim Al-Akhdhar",
    "recite_juhanee": "Awad Al-Juhanee",
    "recite_muhsin": "Abdel-Muhsin Al-Qassem",
    "recite_khaleefa": "Khalefa Al-Tunaiji",
    "recite_ibrahim_dosary": "Ibrahim Al-Dosary",
    "recite_yassin": "Yassin Al-Jazaery",
    "menu_hint": "Main Menu",
    "chooseAya_hint": "To choose the Aya please tap and hold",

    "flash_needed": "You May need flash player to be able to play the audio",
    "trans_ctrl_msg": "Move Up & Down",
    "trans_ctrl_choose": "Change Translation",
    "fontsize": "Font Size",
    "about_title": "Help",
    "about_cont": "This is the mobile interface of the KSU - Electronic Mosshaf project, there are also a PC interface and a downloadable version \"Ayat\" available.",
    "contact_mi": "Contact us",
    "contact_title": "Contact us",
    "contact_name": "Name",
    "contact_email": "Email",
    "contact_msg": "Message",
    "contact_send": "Send",
    "contact_done": "Message Sent Successfully , Thank You",
    "contact_err_name": "Please make sure you typed the name correctly",
    "contact_err_email": "Please make sure you typed the email correctly",
    "contact_err_msg": "Please make sure you typed the message correctly",
    "contact_err_failed": "Sorry message not sent, please try again later",
    "unsub_twitter": "To unsubscribe from Ayat App on Twitter please send us your twitter account url",
    "mosshaf_type": "Moshaf",
    "mosshaf_hafs": "Hafs",
    "mosshaf_tajweed": "Hafs - Tajweed",
    "mosshaf_warsh": "Rewayat Warsh",
    "view_type": "Interface",
    "view_mobile": "Mobile Interface",
    "view_pc": "PC Interface",
    "choose_lang": "Language",
    "l_arabic": "عربي",
    "l_english": "English",
    "fnf_audio": "Sorry, Audio file is not found and cannot be downloaded, check internet connection",
    "fnf_image": "Sorry, Image file is not found and cannot be downloaded, check internet connection",
    "close_app": "Exit from the Application?",
    "close_app_downs": "Exit or Hide Application?, please note exiting App will stop active downloads while hiding will keep it working in the background",
    "sd_nf": "Sorry the Application requires SD card",
    "page_num1604": "Please enter number between 1 and 604",
    "repeat_notifyAway": "Sorry, you are trying to browse Aya out of the repeating boundry, would you like to stop repeating",
    "repeat_notifyStop": "Sorry, you have to deactivate current repeat to enable editing",
    "alert_defTitle": "Alert",
    "alert_ok": "Ok",
    "alert_next": "Next",
    "yes": "Yes",
    "no": "No",
    "downSlowNote": "Caution , During downloading process, you may notice poor performance and unstability in the program, it will be normal when downloading finishes",
    "welcome": "Welcome",
    "intro1": "<p align=\"center\">بسم الله الرحمن الرحيم</p><div><b>Ayat</b> : is a comprehensive Quranic software with unique features </div>",
    "intro2": "To be able to use the application without internet connection, you have to download required contents (images,recitaions,tafasir and tanslations)",
    "intro3": "you can start download required contents by clicking the 'Downloads' button in the main menu",
    "intro4": "<p>Thank you</p> for further help, please click help button in the main menu",
    "help_main_mi": "Usage",
    "help_features_mi": "Features",
    "help_about_mi": "About",
    "help_mi": "Help",
    "pls_wait": "Please wait a moment",
    "favs": "Bookmarks",
    "noFavs": "there are no bookmarks",
    "addFav": "Bookmark",
    "fav_alert": "Add Bookmark",
    "fav_read":"Reading",
    "fav_memo":"Memorizing",
    "fav_readPos":"Reading position",
    "fav_memoPos":"Memorizing position",
    "fav_date":"date",
    

    "note": "Note",
    "optional": "Optional",
    "mtest": "Memorizing test",
    "mtest_ques": "New question",

    
    "buAddFav": "Add",
    "remFav": "remove bookmark",
    "fav_added": "Saved to Bookmarks, you can view bookmarks from 'Browse' menu",
    "fav_exist": "bookmark already exists, would you like to remove it?",
    "copy": "Copy",
    "copy_nextAya": "Next Aya",
    "copy_tashkeel": "Tashkeel",
    
    "copyWOT": "Copy without Tashkeel",
    "send": "Send",
    "sendWOT": "Send without Tashkeel",
    "sendSMS": "send by SMS",
    "sendMail": "send by Email",
    "share": "Share",
    "shareFB": "Facebook",
    "shareTwit": "Twitter",
    "shareApp_bu": "Share App",
    "shareApp_msg": "Ayat - Electronic Mosshaf Project - for PCs and mobile phones, browse Al Quran pages, listen to recitations, read tafasir and translations. available for both online and offline usage : http://quran.ksu.edu.sa",
    "rateApp_bu": "Rate App",
    "bu_closeApp": "Close App",
    "bu_exitApp": "Exit App",
    "bright_type": "Brightness level",
    "bright_high": "high brightness",
    "bright_med": "Medium brightness",
    "vision_type": "View mode",
    "vision_normal": "Normal view",
    "vision_night": "Night view",
    "hint_1": "you can select Aya by double click or Tap and hold",
    "hint_2": "After selecting Aya, a bottom Menu will appear for playing recitation and viewing Tafsir",
    "hint_pls_download": "it's recommended to start download images, recitations and tafasir in order to use the application without internet",
    "hpd_ok": "Download",
    "hpd_no": "Not Now",
    "notify_mob_interface": 'This is the mobile interface, you can switch to the desktop interface via <a href="http://quran.ksu.edu.sa/index.php?ui=1" class="ext">this link</a>',
    "confirm_warsh": "do you want to view the Mosshaf by Rewayat \"Warsh An-Nafie\" ?",
    "confirm_restartApp": "App needs to be restarted to apply this setting, close it now?",


    "setting_keeplight": "Keep lights on",
    "setting_keepworking": "Keep running after locking screen",
    "setting_showstatus": "Show status bar",
    
    "setting_shouldext": "Save recitations on",
    "setting_extsd": "External memory",
    "setting_intsd": "Internal memory",
    
    "extsd_nf" : "Sorry, Ayat couldnt detect the external SD card",

    "download_resumeBu": "Resume",
    "download_pauseBu": "Pause",
    "download_stopBu": "Stop",
    "download_compBu": "Completed",
    "download_pages_from": "From Page",
    "download_pages_to": "To Page",
    "download_masahef": "Moshaf",
    "download_ttarajem": "Tafaser & Translations",
    "download_ttarajem_tafaser": "Tafasir",
    "download_ttarajem_tarajem": "Translations",
    "chk_conn": "Failed to connect to the server, please check your internet connection",

    "confirm_download_tafsir": "Tafsir file doesn't exist, do you want to download it or read directly through internet",
    "confirm_download_trans": "Translation file doesn't exist, do you want to download it or read directly through internet",
    "confirm_download_pages": "Some pages (Quran images) are missing, do you want to download them now?",
    "confirm_update_tafsir": "An update is available for the Tafsir (misspelling corrections), do you want to download it?",
    "confirm_update_trans": "An update is available for the Translation (misspelling corrections), do you want to download it?",

    "direct_read": "Read",
    "download_file": "Download",
    "copy_done": "Copied to the clipboard",
    "copy_failed": "Copy failed",
    "sentViaAyat": "sent via Ayat app",
    "ayaLink": "link",

    "mozaker": "Reminder",
    "mozaker_msg": "Message",
    "mozaker_msg_default": "ورتل القرآن ترتيلا",
    
    "mozaker_alert": "Sound",
    "mozaker_alert_null": "Silent",
    "mozaker_alert_default": "Default",

    "mozaker_null": "Inactive",

    "mozaker_morning": "Morning",
    "mozaker_noon": "Noon",
    "mozaker_evening": "Evening",
    "mozaker_night": "Night",

    "mozaker_am": "AM",
    "mozaker_pm": "PM",
    
    
    "ayatApp": "Ayat",
    "downloadingRecite": "Downloading recitation",
    "downloadingReciteComped": "Completed Downloading recitation",
    "downloadingRecitePaused": "Paused Downloading recitation",
    "recitation": "Recitation",
    "forReciter": "by",
    "downloadingPages":"Downloading pages",
    "downloadingPagesComped":"Completed Downloading pages",
    "downloadingPagesPaused":"Paused Downloading pages",
    "downloadingTTafasir":"Downloading tafair and translations"

};